# Generated by Django 4.1.2 on 2022-10-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.IntegerField()),
                ("nombres", models.CharField(max_length=40)),
                ("apellidos", models.CharField(max_length=40)),
                ("correo", models.CharField(max_length=60)),
                ("contra", models.CharField(max_length=40)),
                ("telefono", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=40)),
                (
                    "usuario_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.usuarios",
                    ),
                ),
            ],
        ),
    ]
