# Generated by Django 4.1.2 on 2022-10-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_documento_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="autor",
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documento",
            name="categoria",
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documento",
            name="descripcion",
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documento",
            name="titulo",
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
