# Generated by Django 4.1.2 on 2022-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_documento_autor_documento_categoria_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documento",
            old_name="cantidad",
            new_name="precio",
        ),
        migrations.AddField(
            model_name="documento",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registro",
            name="cantidad",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
