# Generated by Django 4.1.2 on 2022-10-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documentos",
            "0004_rename_cantidad_documento_precio_documento_stock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="editorial",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="idioma",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="paginas",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
