# Generated by Django 4.1.2 on 2022-10-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0005_documento_editorial_documento_idioma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="hombre",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="mujer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="pais",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="personalizado",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
