# Generated by Django 4.1.2 on 2022-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0006_usuarios_ciudad_usuarios_hombre_usuarios_mujer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="telefono",
        ),
        migrations.AddField(
            model_name="usuarios",
            name="usuario",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="hombre",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="mujer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="personalizado",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
