# Generated by Django 4.1.2 on 2022-10-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0007_remove_usuarios_dni_remove_usuarios_telefono_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarios",
            old_name="hombre",
            new_name="femenino",
        ),
        migrations.RenameField(
            model_name="usuarios",
            old_name="mujer",
            new_name="masculino",
        ),
    ]
