# Generated by Django 4.1.2 on 2022-10-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0008_rename_hombre_usuarios_femenino_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="contra",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="correo",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
