# Generated by Django 4.1.2 on 2022-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0009_alter_usuarios_contra_alter_usuarios_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="usuario",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
